import os

print('                                                     ')
print('#####################################################')
print('                                                     ')
print('mmmmmmm           ===  mmmm')
print('   #   mmm   mmm---H---#   #  mmm   m   m   {0.5#dev}')
print("   #  #' '# #' '# [)]  #mmm' #' '#   #m#")
print('   #  #   # #   # [I]  #   # #   #   m#m')
print('   #  "#m#" "#m#" [I]  #mmm" "#m#"  m" "m')
print(" 		  [I]...")
print('                   V')
print('#####################################################')
print('                                                     ')

os.system('pip install scapy')
os.system('pip install requests')
os.system('pip install fs.smbfs')
os.system('pip install flask')
os.system('pip install paramiko')
os.system('pip install pyinstaller')
os.system('pip install pywifi')
print('[!]需要安装nmap')
print('[*]完成')
